### ISSUE TITLE
Tour Steps Remain Highlighted

### ISSUE THREAD

**Issue by kblazek** [alvaroveliz/aSimpleTour#5]
I've implemented the aSimpleTour and noticed when you click on Previous in the controls the previous steps from the one you are currently on remain highlighted.  I thought I may have missed something in the configuration but I see the same result in the demo.

**Comment by alvaroveliz** [comment]
Thanks for your report. I will fix this soon..

**Comment by alvaroveliz** [comment]
Fixed on version 1.0.7
